### ISSUE TITLE
Make changes necessary for Eucalyptus

### ISSUE THREAD

**Issue by bdero** [mitodl/mitx-theme#3]
I pushed the following commit for Dogwood compatibility:
https://github.com/mitodl/mitx-theme/commit/bed8425939c3f9182764ceac3244f058a610171e

This change should be reverted to make the theme compatible with Eucalyptus when the time comes for it.

**Comment by pdpinch** [comment]
@amir-qayyum-khan do you know if this is still an issue, in particular this [commit comment](https://github.com/mitodl/mitx-theme/commit/bed8425939c3f9182764ceac3244f058a610171e##commitcomment-18543321)?

**Comment by amir-qayyum-khan** [comment]
No need of this in ficus 
```python
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/util/cache.py", line 78, in wrapper
    response = view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/branding/views.py", line 94, in index
    return student.views.index(request, user=request.user)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/views.py", line 221, in index
    return render_to_response('index.html', context)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 198, in render_to_response
    return HttpResponse(render_to_string(template_name, dictionary, context_instance, namespace, request), **kwargs)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 188, in render_to_string
    return template.render_unicode(**context_dictionary)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/template.py", line 454, in render_unicode
    as_unicode=True)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/mako_lms/831340fe3c8114d1c45c5e25cdfe7b73/main.html.py", line 283, in render_body
    runtime._include_file(context, (static.get_template_path('header.html')), _template_uri, online_help_token=online_help_token)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/runtime.py", line 752, in _include_file
    callable_(ctx, **_kwargs_for_include(callable_, context._data, **kwargs))
  File "/tmp/mako_lms/831340fe3c8114d1c45c5e25cdfe7b73/header.html.py", line 34, in render_body
    runtime._include_file(context, (static.get_template_path(relative_path='navigation.html')), _template_uri, online_help_token=online_help_token)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/runtime.py", line 748, in _include_file
    template = _lookup_template(context, uri, calling_uri)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/runtime.py", line 793, in _lookup_template
    return lookup.get_template(uri)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/paths.py", line 74, in get_template
    template = super(DynamicTemplateLookup, self).get_template(get_template_path_with_theme(uri))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/lookup.py", line 253, in get_template
    return self._load(srcfile, uri)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/lookup.py", line 318, in _load
    **self.template_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/compat.py", line 89, in load_module
    return imp.load_source(module_id, path, fp)
  File "/tmp/mako_lms/831340fe3c8114d1c45c5e25cdfe7b73/mitx-theme/lms/templates/navigation.html.py", line 29, in <module>
    from microsite_configuration.templatetags.microsite import platform_name
ImportError: No module named templatetags.microsite
```
